name: ⚖ Bias Mitigation Automation

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '*.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-py:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.11]

    env:
      UCI_DB: "https://archive.ics.uci.edu/ml/machine-learning-databases"
      PROPUBLICA_GH: "https://raw.githubusercontent.com/propublica/compas-analysis/bafff5da3f2e45eca6c2d5055faad269defd135a"
      REPO_KEY: ${{secrets.ETHAI_AUDIT_HUB_GITHUB_TOKEN}}
      username: github-actions

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e '.[all]'
          pip install flake8
          pip list
          python -m rpy2.situation

      - name: Download datasets
        run: |
          wget ${UCI_DB}/adult/adult.data -P aif360/data/raw/adult/
          wget ${UCI_DB}/adult/adult.test -P aif360/data/raw/adult/
          wget ${UCI_DB}/adult/adult.names -P aif360/data/raw/adult/
          wget ${UCI_DB}/statlog/german/german.data -P aif360/data/raw/german/
          wget ${UCI_DB}/statlog/german/german.doc -P aif360/data/raw/german/
          wget ${PROPUBLICA_GH}/compas-scores-two-years.csv -P aif360/data/raw/compas/
          wget ${UCI_DB}/00222/bank-additional.zip -P aif360/data/raw/bank/ && unzip -j aif360/data/raw/bank/bank-additional.zip -d aif360/data/raw/bank/ && rm aif360/data/raw/bank/bank-additional.zip
          (cd aif360/data/raw/meps;Rscript generate_data.R <<< y)

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Download requirements
        run: |
             pwd
             echo pwd
             pip install -r requirements.txt

      - name: Divert to Jupyter notebook directory
        run:  |
              cd  /home/runner/work/EthAIAuditHub/EthAIAuditHub/examples
              ls -a
        
      - name: Execute Jupyter Notebook
        run: |
           pwd
           cd  /home/runner/work/EthAIAuditHub/EthAIAuditHub/examples
           pwd
            # Install nbconvert
            pip install nbconvert
            
            # Execute the Jupyter notebook and save the output to a new notebook
            jupyter nbconvert --to notebook --execute /home/runner/work/EthAIAuditHub/EthAIAuditHub/examples/tutorial_credit_scoring.ipynb --output /home/runner/work/EthAIAuditHub/EthAIAuditHub/examples/output_notebook.ipynb
        
            # Print the contents of the executed notebook
            cat /home/runner/work/EthAIAuditHub/EthAIAuditHub/examples/output_notebook.ipynb
        
        # Add a new step to commit and push the changes
      - name: Commit and Push Changes
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"

      - name: Persist Logs
        run: |
          mkdir -p /home/runner/work/EthAIAuditHub/EthAIAuditHub/automation/artifacts
          cp /home/runner/work/EthAIAuditHub/EthAIAuditHub/examples/output_notebook.ipynb /home/runner/work/EthAIAuditHub/EthAIAuditHub/automation/artifacts/
        if: ${{ always() }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: "Audit Report ${{ github.actor }} - ${{ github.run_number }} - ${{ github.event.head_commit.timestamp | replace(':', '_') }}"
          path: /home/runner/work/EthAIAuditHub/EthAIAuditHub/automation/artifacts

          
      
  build-r:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install R dependencies
        run: install.packages(c("reticulate", "rstudioapi", "testthat"))
        shell: Rscript {0}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install '.[all]'

      - name: Install R package
        run: R CMD INSTALL aif360/aif360-r
